### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#103]
Implement the following hotkeys:

  - [x] `Up/Down`: Moves selection up and down in search, banis, navigator, settings, etc.
  - [x] `Left`: Up
  - [x] `j`: Up
  - [x] `Right`: Down
  - [x] `l` (lowercase L): Down
  - [x] `Page Up`: Up (Used by presenter remotes)
  - [x] `Page Down`: Down
  - [x] `Home`: First line (search result not search bar and nav/bookmarks/etc as expected)
  - [x] `End`: Same logic but with last line.
  - [x] `C-Up`: First line in navigator. Using it on first line will move to last line of previous shabad order ID. Search/Bani/Settings move to first result.
  - [x] `C-Down`: Last line in navigator. Using it on last line will move to first line of next shabad order ID. Search/Bani/Settings move to last result.
  - [x] `Esc`: Clear screen
  - [x] `C-S-b`: Clear screen (used by presenter remotes)
  - [x] `Enter`: activate current line (search, nav, bani, etc). Should work from cleared screen so you can show the same line you were displaying prior to escaping.
  - [x] `Enter`: when used inside the search input box, activate top/first search result.
  - [x] `Spacebar`: autotoggle lines in nav. First use sets "main line", second use from any other line adds new var called "next line" which was the jump line + 1 and goes back to main line. Next line cannot be main line. if shabad has any "rahao" line set as main, none of them can be set as Next line.
  - [x] `b`: autotoggle (used by presenter remotes)
  - [x] `C-Spacebar`: changes the main line to the highlighted line.
  - [x] `S-.`: Always move autotoggle to next line. If already on next line, do nothing. Should not change next line var.
  - [x] `S-,`: Always move autotoggle to main line. If already on main line, do nothing. Should not change any var.
  - [x] `1-G`: Numerical hotkey for 1 - 25 lines. Not to be used on search screen.
  - [x] `C-h`: Toggle built-in controller visibility (hide/show)
  - [x] `C-/`: search page
  - [x] `C-b`: bookmarks page
  - [x] `C-y`: history page
  - [x] `C-Enter`: nav page
  - [x] `C-f`: toggle presenter fullscreen
  - [x] `C-r`: reload/refresh
  - [x] `S-f`: Toggle Controller fullscreen
  - [x] `C-q`: quit all windows of application and possibly preserve state for next startup

Future reservations:

  -  `C-s` or `C-p`: save/print menu for lines/shabad with customizations
  -  `C-c`: copy menu should show additional copy fields in pop-up with different (labelled) hotkeys for fields
  - `C-t`: open new tab
  - `C-w`: close tab
  - `C-n`: open new window
  -  `k`: play/pause (this key is between j and l and works like youtube shortcuts)
  - `S-j`/S-l`: slow-down/speed-up autoplaying navigator

**Comment by Harjot1Singh** [comment]
@bhajneet please modify my initial description with required hotkeys

**Comment by bhajneet** [comment]
Done

We should also address Akhand paath view mode. Should we simply remove it and always allow switching shabads with simply the arrow keys? Should we make it so that on last line the first hit of arrow gives a message "Press again for next shabad"? Then most often people will probably just hit it twice anyways when they want to.

**Comment by Harjot1Singh** [comment]
Thanks.

Could you explain the C-Spacebar one a bit more?

Will the b hotkey not conflict with line hit keys 1-G?

The S-.

**Comment by Harjot1Singh** [comment]
I think we should also have a key for jumping back to the main line, and set the main line to the searched line by default?

**Comment by bhajneet** [comment]
> Could you explain the C-Spacebar one a bit more?

In the case that you auto set line that was searched to main and you need to change what the main line is

> Will the b hotkey not conflict with line hit keys 1-G?

No, this is not alphabetical but by keyboard. 1-0, Q-P, A-G add up to 25 keys.

> The S-. Is a modifier for the behaviour of the auto select, right?
> I think we should also have a key for jumping back to the main line, and set the main line to the searched line by default?

Yes `S-,` is for jumping to main line. Yes, I agree that the line that was searched can be automatically set to main line.

**Comment by bhajneet** [comment]
Changing lines should work with controller hidden/popped out

**Comment by preetcharan** [comment]
@Harjot1Singh @bhajneet 

It was mentioned in Slack about creating a shortcut cmd+c and then a dropdown of options for copying gurbani. This would add a step for me so if possible would like the shortcuts as follows as you created a version for me in the past:

copying should happen without formatting so when you paste elsewhere it pastes in the formatting of the place you're formatting

CMD+G = copy gurbani
CMD+T = copy translit
CMD+E = copy english translation
CMD+A = copy author (I have a suggested format but this is just for basics editing) - Author - Granth - Ang. e.g. Guru Nanak Dev Ji - SGGS Ji - Ang 13

**Comment by bhajneet** [comment]
Though the above hotkey suggestions are not in place and we could implement them on a global level, I think most users would still be confused why cmd+c doesn't work, since that's basically the universal hotkey for copy everywhere else.

So regardless of the suggestions, a cmd+c/three-vertical-dot/right-click menu should be present for those users. This is just one more keypress in the above example. For example instead of CMD+G it would be CMD+C and then G on it's own.

For @preetcharan specific use-case we can either add direct hotkeys for the functions, since we do not use those hotkeys yet. Then if we need to use them for something else, perhaps we can revisit.

Or, ideally, the user should be allowed to set their own hotkeys for functions. We could have a list of "un-hotkeyed" functions at the bottom of the list that the user can supply their own hotkeys for. Or we could even set the hotkey for copy gurbani as CMD+C, G and users like @preetcharan could overwrite that with simply CMD+G.

**Comment by preetcharan** [comment]
Thanks for the reply @bhajneet. If the hotkeys aren't being used, then it being hardcoded in would be great. Otherwise, if it is an option to customise the hotkeys, then as long as it saved on the app so I don't need to set it every time I reopen, that's also fine. There was quite a bit of work @bhajansweet did I think it was, or perhaps yourself with regards to the author formatting for basics editing, so this would most likely have to be hardcoded in. 

For the general user, I imagine that they'd most likely want to copy the whole pangti and not individual elements, that being gurbani in unicode, translit and translation so they can put it into their msg/presentation/social media etc. So perhaps as you hover over you can either select the element or the whole pangti and then choose what to copy.

**Comment by bhajneet** [comment]
https://github.com/ShabadOS/desktop/issues/85

There is also supposed to be a Hindi translit hotkey. With all the different fields that are possible, it might be best to look at a menu instead of direct hotkeys for the general user. However, persistently customized hotkeys should also be possible so the user does not have to customize them on every new update.

**Comment by preetcharan** [comment]
@bhajneet we couldn't solve the hindi issue when we tried it. I am using the GurbaniHindi font which allows me you to write Gurmukhi/Punjabi in Hindi.

**Comment by bhajneet** [comment]
Yes, and now we can use
https://github.com/ShabadOS/gurmukhi-utils/blob/master/lib/toHindi.js

Whether it's included in the sqlite db expor or added as a function in the
program to do it dynamically.

**Comment by Harjot1Singh** [comment]
As a general comment, I think `cmd/ctrl + c` to copy the whole pangti, and sequences like `cmd/ctrl+c g` to copy segments of the pangti is probably the best solution.

With regards to customisable hotkeys, we store the configuration but have no way of updating the current hotkeys. We can create an issue for it to resolve later and it shouldn't be too hard since `react-hotkeys` now offers a `recordHotKey` function to make this easier.

**Comment by bhajneet** [comment]
When using ctrl+c to copy be sure to use the ordering of fields that the projector has.

So if Projector is showing Gurbani, English Translit, and then English Translation use that order. If Projector is showing Gurbani, Hindi Translit, and then Punjabi Darpan use that order.

I'm not sure whether we should be copying the fields that are not being displayed. But perhaps we should?

**Comment by preetcharan** [comment]
@bhajneet i like the idea of being able to copy what you've selected - could be frustrating removing elements of gurbani/translation you've copied even when you haven't selected them they still randomly appear

it means if someone was working on a project they could customise what shabados displays and copy in that way...

this is the generic user, editors like BoS system woudl be different obviously

**Comment by bhajneet** [comment]
In the case that we want to have "autoplay" where you can set the lines to auto-advance every N seconds, we might want to use the `S-,` and `S-.` hotkeys that are currently spec to main or secondary lines. Those are the hotkeys used in YouTube for speeding up and slowing down the video and would translate well to an autoplay feature. Once in autoplay the spacebar would also stop functioning as an autoselector since one normally autoplays to read through (such as during paath) and would instead "pause/play" the lines.

If we want to go that route in the future it might make sense to spec the main/secondary lines away from `<,>` keys and towards `<tab>` and `S-<tab>` instead.

**Comment by bhajneet** [comment]
Weird bugs in search are listed below.

```
ctrl+/ to search
njv
tab
tab
tab
...
tab
```
Every fourth tab key will highlight the search box and the next search result, and if you type anything it will delete the characters in the search box. Also tabs 1n-3n remove focus from search input. Applies to shift+tab as well.

---
```
ctrl+/ to search
hhs
tab x4
sd
down arrow key (doesn't highlight first result)
```
Any search after this with enough results will jump down and start from the previously highlighted line (if the line exist given the number of results of the search query). Contrarily, if there are not enough results for it to highlight the next line (because for some reason it's saving the line from previous searches), then it will fail the down arrow key (at least once).

---
```
ctrl+/ to search
jkmsh
down
up
```
now the typing cursor to input new characters is set to the beginning of the search query. the up and down arrows should not be affecting where the typing cursor is in the search query, only the left and right arrow keys.

---
```
ctrl+/ to search
jkmsh
down
down
```
the search box is highlighted even though it's supposed to be permanently highlighted, instead it should be highlighting the first search result again or it should not be doing anything and staying "stuck" at the last search result. The reverse logic should apply to up arrow on the first search result.

**Comment by bhajneet** [comment]
Please replace the number for the main autoselect line and the jump to line as two different icons (maybe < and > characters if we want to use these two hotkeys as originally specced).

**Comment by Harjot1Singh** [comment]
Awaiting cleanup by @bhajneet before continuation

**Comment by Harjot1Singh** [comment]
All hotkeys should be functional. `S-.` however effectively increments the variable still (in the implementation of auto-select, there is no variable, the next jump position is derived/inferred from the lines viewed and current line position). How useful is this hotkey generally?

**Comment by preetcharan** [comment]
@Harjot1Singh in akhand keertan it's not useful because rarely follows the standard way a shabad is sung, the only useful part of autoselect is the spacebar for home really, that's it, that's my experience anyway generally speaking

**Comment by Sarabveer** [comment]
> 
> 
> @Harjot1Singh in akhand keertan it's not useful because rarely follows the standard way a shabad is sung, the only useful part of autoselect is the spacebar for home really, that's it, that's my experience anyway generally speaking

seconded
