### ISSUE TITLE
Screensaver after 5m { Chromecast }

### ISSUE THREAD

**Issue by bhajansweet** [ShabadOS/desktop#17]

**Comment by Harjot1Singh** [comment]
I'm not sure this is actually desirable behaviour, and if a user wants this, they should configure it at the OS level.

**Comment by bhajneet** [comment]
That is correct for most use cases today (Laptop/Desktop). This feature is actually for the future when we start displaying via Chromecast. Since some TVs can get burn in we thought it would be nice to add an option to show a screensaver of some sort only when there has been no line changes for a lengthy period.

It could also be true that it's not even possible to do this for Chromecast Apps or that it is already built in to Chromecast to do a screensaver. Either way, we still need to play around and test it before we actually think about implementing this. The issue is just a reminder to check it out. Thank you.

**Comment by bhajneet** [comment]
Burn in isn't as big of a problem today. We also can impelement moving backgrounds or something instead. Without a dedicated chromecast app this doesn't make much sense to discuss. Can reopen later if needed.
