### ISSUE TITLE
Replace presenter notifications with Snackbars

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#173]
Requires updating material ui

**Comment by bhajneet** [comment]
I thought we were using the default notifications present in the OS. For instance when it says "So-and-so laptop connected/disconnected".

**Comment by Harjot1Singh** [comment]
We also have in-presenter notifications for things like DB or SOS updated etc, unless we want to delegate that to the OS too?

I think we should have these ones so that we can do in-app alerts/dialogs for analytics etc

**Comment by bhajneet** [comment]
Ok, that makes sense as well -- for example, yes we would like dialogs for
analytics.

I was concerned about users that are in extended display. Will it show that
notification on all Shabad OS windows? What if the window is not maximized
on one of the displays? See third image of new UI discussion
https://github.com/ShabadOS/desktop/issues/164

**Comment by Harjot1Singh** [comment]
Good question. In the v2 UI, it'd be on all screens, I reckon, but in the new UI it should still only be on the controller UI (somehow).

**Comment by bhajneet** [comment]
Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.
