### ISSUE TITLE
Incorrect IP address found

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#190]
```
[start:frontend] Compiled successfully!
[start:frontend] 
[start:frontend] You can now view @shabados/frontend in the browser.
[start:frontend] 
[start:frontend]   Local:            http://localhost:3000/
[start:frontend]   On Your Network:  http://192.168.56.1:3000/
[start:frontend] 
[start:frontend] Note that the development build is not optimized.
[start:frontend] To create a production build, use npm run build.
```

`http://192.168.56.1:3000/` is incorrect. Running ipconfig in cmd will output the correct IP addresses: `192.168.7.212`. This second ip address is what I can use to connect to Shabad OS from a different device on the network.

This needs to eventually be fixed so that we can correctly tell people how to connect from the GUI instead of running terminal commands.

**Comment by Harjot1Singh** [comment]
Two thoughts:

1) it’s create-React-app that lists that IP in dev, so can’t fix this particular instance

2) More importantly, you’re likely getting that IP because you’ve got another network adapter which has a higher priority than your Ethernet adapter. So an option is to list out all active IP addresses, or the hostname (or both).

**Comment by bhajneet** [comment]
Don't need it fixed in create react app, just need to figure out a correct
method for gui later.

No other ip address listed in terminal matched the one found by create
react app.

**Comment by Harjot1Singh** [comment]
Not sure it's possible to find the "correct" IP, but we can certainly send back a list of all IPs
