### ISSUE TITLE
Customisable background

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#21]
Would be good to allow the user to select their own background image.

**Comment by bhajneet** [comment]
Agreed. For now you can change the "logo.png" to affect the Day/Night mode backgrounds, if necessary. Otherwise we can look into adding a GUI option in the future.

**Comment by Harjot1Singh** [comment]
Better to add the GUI option, but this is a suitable workaround for now.

**Comment by bhajneet** [comment]
There is also the "user.css" file that is empty by default. You should be able to place anything in there and override the CSS. So if you'd like to separate backgrounds for Day and Night or if you'd like to fill by width instead of height or vice-versa, it is all possible through there.

We would like this project to be easily "hackable" even if the features aren't there for non-techies just yet. And again, any PRs to include these features are more than welcome. Thank you.

**Comment by Harjot1Singh** [comment]
I like the idea of having a `user.css`.

At some point of maturity, I reckon it'll be better to box the internals, and expose access to things like a `user.css` for advanced users.

**Comment by bhajneet** [comment]
Yeah I believe we have to use an asar for electron-builder for a proper macOS app so we will probably move in that direction of boxing things up.

**Comment by bhajneet** [comment]
Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.

**Comment by bhajneet** [comment]
Would rather take a look at expanding Theme Tool to include display/presenter themes

**Comment by saihaj** [comment]
> Would rather take a look at expanding Theme Tool to include display/presenter themes

https://github.com/ShabadOS/theme-tool/issues/6
