### ISSUE TITLE
installer should include more progress screens

### ISSUE THREAD

**Issue by bhajansweet** [ShabadOS/desktop#302]
when we restarted shabad os to complete the install, there was an installer popup for a few seconds but then nothing for some time. Made me think it was done, but then the shortcut said file doesn't exist, so I was very confused. Waited a few minutes and even went to the website to download the installer manually when it finally reloaded shabad os. So it would be good to have more progress screens during the update to know that it's still working and didn't just fail

**Comment by Harjot1Singh** [comment]
Would a faster install and quicker startup time help with this? Maybe #242 (splash screen) could help.  We basically have very little control over the visuals of the installer (it's using NSIS, recommended by electron-builder), short of changing it from one-click to not.

Perhaps packaging as ASAR would signficantly reduce the time for installation, since lots of files do not have to be extracted.

The reason the shortcut didn't exist is most likely because you interrupted the installer process by trying to open it after it'd finished uninstalling the old version, but it's incredibly frustrating when it happens and I'm still confused on how the dialog disappeared and the installation still wasn't "done"

**Comment by bhajneet** [comment]
Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.
