### ISSUE TITLE
Don't change line when window isn't focused on mouse click

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#388]
Someone may click from a different window onto the main window to focus it, but currently it will also change lines when doing this.

Personally this was how I even figured out we had this feature, however I can see how it would be annoying to some users. So unless the app is already in focus, I don't think we should activate this hotkey.

Thoughts?

**Comment by Harjot1Singh** [comment]
Agreed

**Comment by saihaj** [comment]
What I tried to reproduce this issue:
1. Open shabadOS and display a shabad
2. Hide controller and then click with mouse to change
3. Click on some other window (Vscode in this case) to focus out from shabadOS window
4. Refocusing on shabadOS window, line doesn't change. 
5. Click once more and line changes

From what I understand, on step 4 lines are changing (1 click does that). But for me I have to make one more click to change lines (first click to focus window and then the next click to change line). 

If I am doing this wrong @bhajneet please post the steps. If the expected behavior is take 2 clicks (one to focus window and then other to change line) then I think it might have gotten resolved magically 😄

Note: Tested on dev branch HEAD: c8bd3af3e7b733e18db74b2da3d2ead6356489c8 and release V2.7.0 on MacOS 10.15.5

**Comment by bhajneet** [comment]
This is how I reproduced on dev branch using `npm start`

![issue](https://user-images.githubusercontent.com/14130567/83290725-1d3e5c00-a1b5-11ea-8cf5-5ca7f4ca66b8.gif)

**Comment by saihaj** [comment]
Platform specific issue 

![2020-05-29 13 08 38](https://user-images.githubusercontent.com/44710980/83291226-a05bb400-a1ad-11ea-8ddd-5431b9c77694.gif)

**Comment by Harjot1Singh** [comment]
Mac and windows handle focus events differently. Namely, Mac does not allow clicks until the window is focused (so you must double-click to click a line), whilst in Windows, anything can be clicked, focus or not. Thus, it should be noted that on Windows, both `focus` and `click` fire at the same time, which is a little frustrating.

Two solutions I played with:
1) Allow mouse-click slides only once a defocused window has been clicked once. The downside is that clicking the current taskbar will not trigger this, and therefore in circumstance that a user focuses the window by clicking the taskbar, and then the screen, an extra click will be required.

2) Adding a timeout to the onFocus event, so that when the click is fired at the same time, it will be ignored. However, the downside of this is that `onClick` actually fires only on `mouseUp`, which means that if the user clicks on the screen slowly or holds the mouse longer than the timeout, the line will change.

I lean towards solution 1. Thoughts @bhajneet?

TTR: 1hr

**Comment by bhajneet** [comment]
1 is good to go
