### ISSUE TITLE
Setup backend CLI

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#41]
Be nice if we could do:
```
npm install -g @shabados/backend  # Install shabadOS as a CLI tool via npm
@shabados/backend  # Launch shabadOS backend
```
For linux/those who want a shell only, with updates.

**Comment by bhajneet** [comment]
What would they do with the backend in CLI?

**Comment by bhajneet** [comment]
Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.
