### ISSUE TITLE
Add fixed box constraint (Settings > Overlay)

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/desktop#47]
In live caption tool, allow the option to set the bounding box to a fixed size, and have the font auto-scale. Refer to work done for STV.

**Comment by bhajneet** [comment]
Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.
