### ISSUE TITLE
Crtl-Up/Down Hotkey doesn't change shabad on First/Last line

### ISSUE THREAD

**Issue by Sarabveer** [ShabadOS/desktop#504]
Crtl-Up and Crtl-Down changes the line to the first/last line respectively, but doesn't change the shabad when used again

**Comment by bhajneet** [comment]
Looks like this is taking precedence:

![image](https://user-images.githubusercontent.com/14130567/83289537-30e8c300-a1b3-11ea-97bd-ec6f0c08cb6a.png)

![image](https://user-images.githubusercontent.com/14130567/83289650-5970bd00-a1b3-11ea-94ce-eb73ad03450a.png)

Which maybe doesn't allow these to fire?

![image](https://user-images.githubusercontent.com/14130567/83289745-7b6a3f80-a1b3-11ea-9e2a-17664a656e55.png)

Any guidance @Harjot1Singh ?

**Comment by bhajneet** [comment]
If I delete 183 and 184 from `withNavigationHotkeys` it starts to work correctly, so I believe the issue is with the hotkeys precedence being over-ridden by `NavigationHotkeys.js`

No idea on how to solve though

**Comment by Harjot1Singh** [comment]
Good investigative work.

A cheeky but acceptable way to solve this would be to disable those hotkeys inside `withNavigationHotkeys` when in the navigator. The downside of this would be that you'd lose debounce for `home/ctrl-up` + `end/ctrl-down` keys. Which I think is OK in this instance since you can still use `up/down` and the other hotkeys straight after with debounce (but I think if you hit `end up up`, you'll end up with a transition to the last line and second last line, and then debounce will kick in, instead of a transition to only the last line)

To go about this, note `L189` in `withNavigationHotkeys`. Can't remember how it's passed in, but just pass in `{ first: null, last: null }` for the keymap in `Navigator.js`. I think it might be suppliable where `withNavigationHotkeys( Navigator )` is called, but do check.
