### ISSUE TITLE
Incorrectly vertically padded buttons in settings

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#519]
![image](https://user-images.githubusercontent.com/14130567/81874625-3fe13b80-954c-11ea-8b96-81233911a5a2.png)

The buttons have less space at the red lines than they do between each other or settings toggles have between themselves

**Comment by saihaj** [comment]
I don't think that bottom one is different because it the last item adds padding exactly the same as other options have. `Learn more` button's padding definitely has issues and that will be fixed.
![image](https://user-images.githubusercontent.com/44710980/86946802-85675280-c110-11ea-92b6-be205bdc6be5.png)
