### ISSUE TITLE
How do I find the web address to be able to connect other devices

### ISSUE THREAD

**Issue by Jugindersingh** [ShabadOS/desktop#6]
When hovering over title bar, can only see the current computer/laptop name; no web address.

**Comment by Harjot1Singh** [comment]
You can see the address in the live captions tool, but otherwise the address is `http://ip_address_or_computer_name:42424/display` for the full display, and `http://ip_address_or_computer_name:42424` for just the controller.

**Comment by bhajneet** [comment]
Some options:

* You can use another desktop/laptop's Shabad OS via Menu > Connect To...
* If on the same computer / device you can use `http://localhost:42424/`
* Otherwise there is the built in "Copy URL" which will show you the base IP address of the device in Menu > Live Captions Tool

![untitled](https://user-images.githubusercontent.com/14130567/39667735-91026722-508a-11e8-9207-09d6a57c6da7.png)

**Comment by Jugindersingh** [comment]
That's excellent and sorry for not realising it was so easy. Didn't fully understand the live caption tool earlier.

Is it possible to connect via the internet or does this has to be via an internal router? i.e. could the laptop etc be connected to router but a phone could connect via its mobile internet connection? I guess it would need some dynamic ip set up but could be outside the scope of shabad os?

**Comment by bhajneet** [comment]
You could with a VPN I suppose. Otherwise we're going to implement connecting through the shabados.com servers at a later date. This should help with multiple Live Streamers patching into the same central Shabad OS captioning. Thank you for the suggestion and your patience :) Let us know if there is anything else in a different issue!

**Comment by Harjot1Singh** [comment]
You could also port forward `42424` and have a dynamic DNS or static IP setup to access it remotely.

**Comment by bhajneet** [comment]
I can understand how it works with a static IP (but in the states that costs extra I imagine). How does the dynamic DNS work?

**Comment by Harjot1Singh** [comment]
There are many services like [no-ip](https://www.noip.com/), where you run a daemon on your PC, and it updates a hostname they provide automatically (so no need for a static IP).

**Comment by Jugindersingh** [comment]
Yes, exactly. Nice to talk to sangat with tech knowledge!
