### ISSUE TITLE
Re-Implement "Connect To..." Functionality

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#84]
Golang version used mDNS as a discovery protocol to find other Shabad OS servers.

Node version should try to maintain a list of Shabad OS servers that are on the same network (and in the future, extend to something where Shabad OS instances that are physically close in proximity can connect, similar to how Chromecast works).

Related issues:

#45 to create hotspots, this could tie in with physically near shabad os devices
#7 for some discussion on connect to
#24 for adding pin protection access to connect to for certain functionalities (don't allow full take over of screens, don't allow settings changes, etc without pin access perhaps)

**Comment by Harjot1Singh** [comment]
Some of my thoughts:

The previous Golang version required Bonjour or some sort of mDNS stack to be installed on the target machine. I'd like to move away from this - perhaps another discovery mechanism that's not mDNS based would be better. I saw a couple of npm libraries that could achieve this.

It would be good to generalise this implementation so that different "sources" of devices can be fed to the "connect-to" list, e.g. close proximity, same network etc as two different sources, but appear in the same list.

**Comment by sbaljeet13** [comment]
🛠  Working on it 🚧

**Comment by bhajneet** [comment]
Any progress @sbaljeet13 ?

**Comment by sbaljeet13** [comment]
I am using `network-list` npm module which scans the network and provides ip address, mac addresses, vendor and other info about devices connected on the network. I am working on the logic to check which of those devices are running ShabadOS and eventually try to connect with them.

Do we have code for the Golang version of the app? The logic how this functionality was implemented in that will help me to not reinvent the wheel again.

**Comment by bhajneet** [comment]
Close in favor of #416 ?

**Comment by sbaljeet13** [comment]
Unassigning myself since I am not actively working on it.
