### ISSUE TITLE
API

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/desktop#89]
If there was an API that lets users query current line's metadata or entire shabad of current line they could potentially use that text in things like hukamnama displays, live caption tools that don't support web, or post-production examples for copying multiple things at once.

**Comment by bhajneet** [comment]
If you can change the shabad/line through the API, then maybe we can integrate some kind of extension for final cut pro in post-production to improve the speed with which BoS add slides to their videos

**Comment by Harjot1Singh** [comment]
We already technically have a WebSocket API that anyone can subscribe to for updates

**Comment by bhajneet** [comment]
Checkout workflow extensions in here: https://www.apple.com/final-cut-pro/resources/ecosystem/

@preetcharan do you think something like this would be easily possible with BoS videos?

**Comment by preetcharan** [comment]
> Checkout workflow extensions in here: https://www.apple.com/final-cut-pro/resources/ecosystem/
> 
> @preetcharan do you think something like this would be easily possible with BoS videos?

Yeah @bhajneet could really be useful - at the moment it's not so bad because I separate shabad os from the viwer window and it stays on top so switching and copying/pasting elements is fast - but if somehow could integrate it and speed it up even more that would be amazing - not sure how it could be quicker and how it'd be but if it's not a huge effort to integrate it, worth testing it and seeing how it is!

**Comment by bhajneet** [comment]
This issue and it's resolution / application is vague. I believe the hotkeys work will resolve this issue.
